from setuptools import setup, find_packages

setup(
    name="polar-nlp",
    version="0.2.0",
    description="TR-KABÜ Psikososyal Risk Tarama Sistemi - BERTurk + Stilometri Hibrit NLP",
    long_description=open("README.md", "r", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="Efe Ağlamazlar",
    author_email="",
    url="https://github.com/aglamazlarefe/Polar_NLP",
    packages=find_packages(include=["polar_nlp", "polar_nlp.*"]),
    include_package_data=True,
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.35.0",
        "accelerate>=0.24.0",
        "datasets>=2.14.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "streamlit>=1.28.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "Pillow>=10.0.0",
        "python-docx>=0.8.11",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: Turkish",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Text Processing :: Linguistic",
    ],
    python_requires=">=3.10",
)